### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by kyawswar** [dwijitsolutions/laraadmin-crm#1]
I typed the "php artisan la:install". 
deleted the some controller files(contacts,tickets...)
and can't migrate.
show error
LAInstall::handle exception: ErrorException: Undefined offset: 0 in /Applications/XAMPP/xamppfiles/htdocs/laraadmin-crm/vendor/dwij/laraadmin/src/Models/Module.php:716
Stack trace:
....

how can i do that?

already updated "composer update dwij/laraadmin"

typed "php artisan migrate:status"
show below message
------+---------------------------------------------------+
| Ran? | Migration                                         |
+------+---------------------------------------------------+
| Y    | 2014_05_26_050000_create_modules_table            |
| Y    | 2014_05_26_055000_create_module_field_types_table |
| Y    | 2014_05_26_060000_create_module_fields_table      |
| Y    | 2014_10_12_000000_create_users_table              |
| Y    | 2014_10_12_100000_create_password_resets_table    |
| Y    | 2014_12_01_000000_create_uploads_table            |
| Y    | 2016_05_26_064006_create_departments_table        |
| Y    | 2016_05_26_064007_create_employees_table          |
| Y    | 2016_05_26_064446_create_roles_table              |
| Y    | 2016_07_05_115343_create_role_user_table          |
| Y    | 2016_07_06_1406376_create_industry_types_table    |
| Y    | 2016_07_06_140637_create_organizations_table      |
| Y    | 2016_07_07_134058_create_backups_table            |
| Y    | 2016_07_07_134058_create_menus_table              |
| Y    | 2016_09_10_163337_create_permissions_table        |
| Y    | 2016_09_10_163520_create_permission_role_table    |
| Y    | 2016_09_22_105958_role_module_fields_table        |
| Y    | 2016_09_22_110008_role_module_table               |
| Y    | 2016_10_06_115413_create_la_configs_table         |
| N    | 2016_11_16_123515_create_contacts_table           |
| N    | 2016_11_17_063011_create_leads_table              |
| N    | 2016_11_17_064710_create_opportunities_table      |
| N    | 2016_11_17_080230_create_projects_table           |
| N    | 2016_11_17_093246_create_tickets_table            |
+------+---------------------------------------------------+

please help me. thanks

**Comment by Sohail05** [comment]
Hi @kyawswar, 
did you happen to get it running?

I found that the error originated from `Module::format_fields` Causing an `Undefined offset: 0`.
It's the same error you are getting in `/dwij/laraadmin/src/Models/Module.php:716`.

**Comment by robyirloreto** [comment]
LAInstall::handle exception: ErrorException: copy(C:\xampp\htdocs\mundialgifts/app/Http/Controllers/LA/BackupsController.php): failed to open stream: Permission denied in C:\xampp\htdocs\mundialgifts\vendor\dwij\laraadmin\src\Helpers\LAHelper.php:150
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'copy(C:\\xampp\\h...', 'C:\\xampp\\htdocs...', 150, Array)
#1 C:\xampp\htdocs\mundialgifts\vendor\dwij\laraadmin\src\Helpers\LAHelper.php(150): copy('C:\\xampp\\htdocs...', 'C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\mundialgifts\vendor\dwij\laraadmin\src\Commands\LAInstall.php(354): Dwij\Laraadmin\Helpers\LAHelper::recurse_copy('C:\\xampp\\htdocs...', 'C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\mundialgifts\vendor\dwij\laraadmin\src\Commands\LAInstall.php(114): Dwij\Laraadmin\Commands\LAInstall->replaceFolder('C:\\xampp\\htdocs...', 'C:\\xampp\\htdocs...')
#4 [internal function]: Dwij\Laraadmin\Commands\LAInstall->handle()
#5 C:\xampp\htdocs\mundialgifts\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\mundialgifts\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#7 C:\xampp\htdocs\mundialgifts\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\xampp\htdocs\mundialgifts\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 C:\xampp\htdocs\mundialgifts\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 C:\xampp\htdocs\mundialgifts\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Dwij\Laraadmin\Commands\LAInstall), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\xampp\htdocs\mundialgifts\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\xampp\htdocs\mundialgifts\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\xampp\htdocs\mundialgifts\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}


  [Exception]
  LAInstall::handle Unable to install : copy(C:\xampp\htdocs\mundialgifts/app
  /Http/Controllers/LA/BackupsController.php): failed to open stream: Permiss
  ion denied

**Comment by stephanieagillen** [comment]
> Hi @kyawswar,
> did you happen to get it running?
> 
> I found that the error originated from `Module::format_fields` Causing an `Undefined offset: 0`.
> It's the same error you are getting in `/dwij/laraadmin/src/Models/Module.php:716`.

Is there a solution to this issue? I see it is stemming from `Module::format_fields` on line 58 but what do you do?
